### ISSUE TITLE
#warning ROBERT TODO - all kinds of disabled stuff

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/ztracker_mac#2]
There are dozens and dozens of disabled things with 
```#warning ROBERT TODO```

in the sourcecode, which have been disabled by @CrossProd originally, because of going for the shortest route of getting the application to compile. Lots of dependencies too, such as WindowsTimer and that kind of stuff.

These would need to be addressed by someone who knows what they are doing.

**Comment by esaruoho** [comment]
- [ ] OutputDevices.h
- [ ] module.cpp
- [ ] WindowsTimer.cpp
- [ ] main.cpp
- [ ] zlib_wrapper.cpp
- [ ] UserInterface.cpp
- [ ] ztfile-io.cpp
- [ ] CUI_SaveMsg.cpp
- [ ] WindowsThreading.cpp
- [ ] skins.cpp
- [ ] OutputDevices.cpp
- [ ] WindowsMidi.mm
- [ ] playback.cpp
- [ ] CUI_LoadMsg.cpp
